temp
Signed-off-by: Francesco Torchia <francesco.torchia@suse.com>

diff --git a/shell/scripts/extension/publish b/shell/scripts/extension/publish
--- a/shell/scripts/extension/publish
+++ b/shell/scripts/extension/publish
@@ -2,6 +2,7 @@
 
 SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
 BASE_DIR="$(pwd)"
+BASE_EXT=$(basename ${BASE_DIR})
 
 CYAN="\033[96m"
 YELLOW="\033[93m"
@@ -16,33 +17,25 @@ REGISTRY_ORG=""
 IMAGE_PREFIX="ui-extension-"
 FORCE="false"
 GITHUB_BUILD="true"
-GITHUB_RELEASE_TAG=""
-PODMAN_CONTAINER="false"
-UPDATE_OLD_PACKAGES="true"
-UPDATE_LATEST_PACAKGES="true"
 
 GITHUB_SOURCE=$(git config --get remote.origin.url | sed -e 's/^git@.*:\([[:graph:]]*\).git/\1/')
 GITHUB_BRANCH="main"
 
 usage() {
-  echo "Usage: $0 [<options>] [extensions]"
+  echo "Usage: $0 [<options>] [plugins]"
   echo " options:"
-  echo "  -s <repo>    Specify destination GitHub repository (org/name) - defaults to the git origin"
-  echo "  -b <branch>  Specify destination GitHub branch"
-  echo "  -t <tag>     Specify the Github release tag to build when a release has been tagged and published"
-  echo "  -f           Force building the chart even if it already exists"
-  echo "  -c           Build as a container image rather than publishing to Github"
   echo "  -p           Push container images on build"
+  echo "  -f           Force building the chart even if it already exists"
   echo "  -r <name>    Specify destination container registry for built images"
   echo "  -o <name>    Specify destination container registry organization for built images"
   echo "  -i <prefix>  Specify prefix for the built container image (default: 'ui-extension-')"
-  echo "  -l           Specify Podman container build"
-  echo "  -n           Do not check for updates to existing Charts (Chart.yaml)"
-  echo "  -e           Only check for updates to existing Charts (Chart.yaml)"
+  echo "  -c           Build as a container image rather than publishing to Github"
+  echo "  -s <repo>    Specify destination GitHub repository (org/name) - defaults to the git origin"
+  echo "  -b <branch>  Specify destination GitHub branch"
   exit 1
 }
 
-while getopts "hvr:o:pi:fcb:t:s:lne" opt; do
+while getopts "hvr:o:pi:fcb:s:" opt; do
   case $opt in
     h)
       usage
@@ -73,19 +66,6 @@ while getopts "hvr:o:pi:fcb:t:s:lne" opt; do
       GITHUB_BUILD="true"
       GITHUB_BRANCH="${OPTARG}"
       ;;
-    t)
-      GITHUB_RELEASE_TAG="${OPTARG}"
-      ;;
-    l)
-      PODMAN_CONTAINER="true"
-      ;;
-    n)
-      UPDATE_OLD_PACKAGES="false"
-      ;;
-    e)
-      UPDATE_OLD_PACKAGES="true"
-      UPDATE_LATEST_PACAKGES="false"
-      ;;
     *)
       usage
       ;;
@@ -97,7 +77,7 @@ shift $((OPTIND-1))
 PLUGINS=( "$@" )
 BUILT="false"
 
-echo -e "${CYAN}${BOLD}Publishing UI Extensions${RESET}"
+echo -e "${CYAN}${BOLD}Publishing UI Plugins${RESET}"
 
 pushd ${BASE_DIR} > /dev/null
 
@@ -110,10 +90,6 @@ if [ "${GITHUB_BUILD}" == "true" ]; then
 
   echo -e "${CYAN}GitHub Repository: ${GITHUB_SOURCE}${RESET}"
   echo -e "${CYAN}GitHub Branch    : ${GITHUB_BRANCH}${RESET}"
-
-  if [[ -n "${GITHUB_RELEASE_TAG}" ]]; then
-    echo -e "${CYAN}GitHub Release   : ${GITHUB_RELEASE_TAG}${RESET}"
-  fi
 else
   echo -e ${CYAN}"Image prefix: ${IMAGE_PREFIX}${RESET}"
 fi
@@ -140,15 +116,7 @@ if ! [[ -d ${BASE_DIR}/node_modules ]]; then
   exit 1
 fi
 
-COMMANDS=("node" "jq" "yq" "git" "helm" "yarn")
-if [ "${GITHUB_BUILD}" == "false" ]; then
-  if [ "${PODMAN_CONTAINER}" == "true" ]; then
-    COMMANDS+=("podman")
-  else
-    COMMANDS+=("docker")
-  fi
-fi
-
+COMMANDS=("node" "jq" "yq" "git" "docker" "helm" "yarn")
 HAVE_COMMANDS="true"
 for CMD in "${COMMANDS[@]}"
 do
@@ -164,15 +132,7 @@ fi
 
 # --------------------------------------------------------------------------------
 # Only do conatiner args checks if not GitHub publish
-# --------------------------------------------------------------------------------
 if [ "${GITHUB_BUILD}" == "false" ]; then
-  BASE_EXT=$(jq -r .name ${BASE_DIR}/package.json)
-  EXT_VERSION=$(jq -r .version ${BASE_DIR}/package.json)
-
-  if [ -z ${EXT_VERSION} ]; then
-    EXT_VERSION="0.0.0"
-  fi
-
   if [[ -z ${REGISTRY_ORG} ]]; then
     # Infer that the user has the same Docker registry org as their GitHub org
     GITHUB_REPO=$(git config --get remote.origin.url | sed -e 's/^git@.*:\([[:graph:]]*\).git/\1/')
@@ -186,18 +146,10 @@ if [ "${GITHUB_BUILD}" == "false" ]; then
     exit 1
   fi
 
-  if [ -n "${GITHUB_RELEASE_TAG}" ] && [[ ${GITHUB_RELEASE_TAG} != "${BASE_EXT}-${EXT_VERSION}" ]]; then
-    echo -e "${YELLOW}Github tagged release name does not match ${RESET}${BOLD}${BASE_EXT}-${EXT_VERSION}${RESET}"
-    echo -e "${YELLOW}Stopping build${RESET}"
+  docker images > /dev/null
+  if [ $? -ne 0 ]; then
+    echo "docker is not running - this is required to build container images for the UI Plugins"
     exit 1
-  fi
-
-  if [ "${PODMAN_CONTAINER}" == "false" ]; then
-    docker images > /dev/null
-    if [ $? -ne 0 ]; then
-      echo "docker is not running - this is required to build container images for the UI Extensions"
-      exit 1
-    fi
   fi
 fi
 
@@ -222,236 +174,158 @@ CHART_TEMPLATE=${BASE_DIR}/tmp/helm
 ROOT_INDEX=${BASE_DIR}/index.yaml
 
 # --------------------------------------------------------------------------------
-# Iterate through all existing charts and look for updates/removals
-# --------------------------------------------------------------------------------
-if [ "${UPDATE_OLD_PACKAGES}" = "true" ]; then
-  pushd ${ASSETS} > /dev/null
-  echo -e "${CYAN}${BOLD}Checking existing charts for updates ...${RESET}"
-
-  for FOLDER_NAME in */ ; do
-    EXT_NAME=${FOLDER_NAME::${#FOLDER_NAME}-1}
-    echo -e "${CYAN}${EXT_NAME}${RESET}"
-
-    for CHART_ARCHIVE in ${EXT_NAME}/*.tgz ; do
-      rm -f ${TMP}/Chart.yaml
-
-      # path in chart may be different to tar file name, so extratct the Chart.yaml file to the top-level folder
-      tar --strip-components=1 -C ${TMP} -xf ${CHART_ARCHIVE} */Chart.yaml
-
-      EXISTING_MD5=$(md5 -q ${TMP}/Chart.yaml)
-      VERSION=$(yq eval .version ${TMP}/Chart.yaml)
-
-      CHART_FOLDER=${CHARTS}/${EXT_NAME}/${VERSION}
-      LATEST=${CHART_FOLDER}/Chart.yaml
-
-      if [ ! -f "${LATEST}" ]; then
-        echo "  - Chart for ${EXT}-${VERSION} appears to have been deleted - removing chart archive: ${CHART_ARCHIVE}"
-        rm -f ${ASSETS}/${CHART_ARCHIVE}
-        BUILT="true"
-      else
-        # Re-package the helm chart so that the Chart.yaml is processed in the same way so we can compare it
-        mkdir -p ${TMP}/tmp_chart
-        helm package ${CHART_FOLDER} -d ${TMP}/tmp_chart > /dev/null
-        rm ${TMP}/Chart.yaml
-
-        # path in chart may be different to tar file name, so list the files to find what the chart archive is named
-        FILENAME=$(cd ${TMP}/tmp_chart; ls)
-
-        # path in chart may be different to tar file name, so extratct the Chart.yaml file to the top-level folder
-        tar --strip-components=1 -C ${TMP} -xf ${TMP}/tmp_chart/${FILENAME} */Chart.yaml
-        LATEST_MD5=$(md5 -q ${TMP}/Chart.yaml)
-
-        rm -f $TMP/tmp_chart/${FILENAME}
-
-        if [ "${EXISTING_MD5}" != "${LATEST_MD5}" ]; then
-          BUILT="true"
-
-          echo "  + Chart.yaml has changed for ${CHART_ARCHIVE}"
-          # Chart was already re-generated - update ir
-          rm ${CHART_ARCHIVE}
-          helm package ${CHART_FOLDER} -d ${ASSETS}/${EXT_NAME}
-        fi
-      fi
-
-      rm -d ${TMP}/tmp_chart
-      rm ${TMP}/Chart.yaml
-      
-    done
-  done
-
-  popd > /dev/null
-fi
-
-# --------------------------------------------------------------------------------
 # Iterate through all packages - built them all or build only those specified on the command line
 # --------------------------------------------------------------------------------
-if [ "${UPDATE_LATEST_PACAKGES}" = "true" ]; then
-  for d in pkg/*/ ; do
-    pkg=$(basename $d)
+for d in pkg/*/ ; do
+  pkg=$(basename $d)
 
-    if [ -z "$1" ] || [[ " ${PLUGINS[*]} " =~ " ${pkg} " ]]; then
-      # Check we don't already have a published version by looking in the assets folder
-      PKG_VERSION=$(jq -r .version ./pkg/${pkg}/package.json)
-      PKG_NAME="${pkg}-${PKG_VERSION}"
-      PKG_ASSET=${ASSETS}/${pkg}/${PKG_NAME}.tgz
+  if [ -z "$1" ] || [[ " ${PLUGINS[*]} " =~ " ${pkg} " ]]; then
+    # Check we don't already have a published version by looking in the assets folder
+    PKG_VERSION=$(jq -r .version ./pkg/${pkg}/package.json)
+    PKG_NAME="${pkg}-${PKG_VERSION}"
+    PKG_ASSET=${ASSETS}/${pkg}/${PKG_NAME}.tgz
 
-      # Skip the build for a package that does not match the tagged release name
-      if [[ -n "${GITHUB_RELEASE_TAG}" ]] && [ ${GITHUB_BUILD} == "true" ] && [[ ${GITHUB_RELEASE_TAG} != ${PKG_NAME} ]]; then
-        echo -e "${YELLOW}Github release tag ${RESET}${BOLD}${GITHUB_RELEASE_TAG}${RESET}${YELLOW} does not match asset name${RESET}"
-        echo -e "${YELLOW}Skipping ${RESET}${BOLD}${PKG_NAME}${RESET}"
-        continue
-      fi
+    echo -e "${CYAN}${BOLD}Building plugin: ${pkg} (${PKG_VERSION}) ${RESET}"
 
-      echo -e "${CYAN}${BOLD}Building extension: ${pkg} (${PKG_VERSION}) ${RESET}"
+    echo "Package version: ${PKG_VERSION}"
+    echo "Package folder:  ${PKG_NAME}"
 
-      echo "Package version: ${PKG_VERSION}"
-      echo "Package folder:  ${PKG_NAME}"
+    # --------------------------------------------------------------------------------
+    # Build the plugin from source
+    # --------------------------------------------------------------------------------
+    echo -e "${CYAN}Building plugin from source code${RESET}"
+    FORCE_COLOR=1 yarn build-pkg $pkg | cat
 
-      # --------------------------------------------------------------------------------
-      # Build the plugin from source
-      # --------------------------------------------------------------------------------
-      echo -e "${CYAN}Building extension from source code${RESET}"
-      FORCE_COLOR=1 yarn build-pkg $pkg | cat
+    echo -e "${CYAN}Adding plugin code ...${RESET}"
 
-      echo -e "${CYAN}Adding extension code ...${RESET}"
+    EXT_FOLDER=${BASE_DIR}/extensions/${pkg}/${PKG_VERSION}
+    PKG_DIST="${BASE_DIR}/dist-pkg/${PKG_NAME}"
 
-      EXT_FOLDER=${BASE_DIR}/extensions/${pkg}/${PKG_VERSION}
-      PKG_DIST="${BASE_DIR}/dist-pkg/${PKG_NAME}"
+    rm -rf ${EXT_FOLDER}
 
-      rm -rf ${EXT_FOLDER}
+    mkdir -p ${EXT_FOLDER}/plugin
 
-      mkdir -p ${EXT_FOLDER}/plugin
+    # Copy the code into the folder
+    cp -R ${PKG_DIST}/* ${EXT_FOLDER}/plugin
 
-      # Copy the code into the folder
-      cp -R ${PKG_DIST}/* ${EXT_FOLDER}/plugin
+    pushd ${BASE_DIR}/extensions/${pkg}/${PKG_VERSION} > /dev/null
+    rm -f plugin/report.html
+    find plugin -type f | sort > files.txt
+    popd > /dev/null
 
-      pushd ${BASE_DIR}/extensions/${pkg}/${PKG_VERSION} > /dev/null
-      rm -f plugin/report.html
-      find plugin -type f | sort > files.txt
-      popd > /dev/null
+    # --------------------------------------------------------------------------------
+    # Create the Helm chart
+    # --------------------------------------------------------------------------------
 
-      # --------------------------------------------------------------------------------
-      # Create the Helm chart
-      # --------------------------------------------------------------------------------
-
-      if [ -f ${PKG_ASSET} ] && [ "${FORCE}" == "false" ]; then
-        echo -e "${YELLOW}Helm chart has already been created - skipping (run with -f to force build)${RESET}"
-        continue;
-      fi
-
-      CHART_FOLDER=${CHARTS}/${pkg}/${PKG_VERSION}
-
-      mkdir -p ${ASSETS}/${pkg}
-      rm -rf ${CHART_FOLDER}
-      mkdir -p ${CHART_FOLDER}
-
-      cp -R ${CHART_TEMPLATE}/charts/ui-plugin-server/* ${CHART_FOLDER}
-
-      # Update Chart.yaml and values.yaml from the package file metadata
-      # Use the script from the template repository
-      echo -e "${CYAN}Patching Helm chart template${RESET}"
-
-      CHART=${CHART_FOLDER} REGISTRY="${REGISTRY}" ORG="${REGISTRY_ORG}" PACKAGE_JSON=${BASE_DIR}/pkg/${pkg}/package.json ${CHART_TEMPLATE}/scripts/patch
-
-      # Copy README file from the plugin to the Helm chart, if there is one
-      if [ -f "./pkg/${pkg}/README.md" ]; then
-        cp ./pkg/${pkg}/README.md ${CHART_FOLDER}/README.md
-      fi
-
-      pushd ${CHART_FOLDER}/templates > /dev/null
-      
-      if [ "${GITHUB_BUILD}" == "true" ]; then
-        echo "Patching for GitHub build"
-        ENDPOINT=https://raw.githubusercontent.com/${GITHUB_SOURCE}/${GITHUB_BRANCH}/extensions/${pkg}/${PKG_VERSION}
-      else
-        echo "Patching for container build"
-        ENDPOINT=http://${IMAGE_PREFIX}${BASE_EXT}-svc.cattle-ui-plugin-system:8080/plugin/${PKG_NAME}
-      fi
-      sed -i.bak -e 's@endpoint: .*@endpoint: '"${ENDPOINT}"'@g' cr.yaml
-      rm *.bak
-      popd > /dev/null
-
-      # Additional patches
-      ${SCRIPT_DIR}/helmpatch ${CHART_FOLDER} "${BASE_DIR}/pkg/${pkg}/package.json"
-
-      # Package into a .tgz helm chart
-      helm package ${CHART_FOLDER} -d ${ASSETS}/${pkg}
-
-      BUILT="true"
+    if [ -f ${PKG_ASSET} ] && [ "${FORCE}" == "false" ]; then
+      echo -e "${YELLOW}Helm chart has already been created - skipping (run with -f to force build)${RESET}"
+      continue;
     fi
-  done
-fi
 
-# Update the Helm Index for all charts, if changes were made
-if [ "${BUILT}" == "true" ]; then
-  # --------------------------------------------------------------------------------
-  # Update the helm index for all charts
-  # --------------------------------------------------------------------------------
-  HELM_INDEX=${BASE_DIR}/index.yaml
+    CHART_FOLDER=${CHARTS}/${pkg}/${PKG_VERSION}
 
-  echo "Updating Helm Index file"
+    mkdir -p ${ASSETS}/${pkg}
+    rm -rf ${CHART_FOLDER}
+    mkdir -p ${CHART_FOLDER}
 
-  if [ -f "${HELM_INDEX}" ]; then
-    UPDATE="--merge ${HELM_INDEX}"
-  elif [ "${GITHUB_BUILD}" == "true" ] && [[ -n ${GITHUB_SOURCE} ]]; then
-    # Check if git branch contains index.yaml
-    GITHUB_SOURCE=$(echo -e "${GITHUB_SOURCE}" | sed 's/https:\/\///g')
+    cp -R ${CHART_TEMPLATE}/charts/ui-plugin-server/* ${CHART_FOLDER}
 
-    wget -P ${BASE_DIR} https://raw.githubusercontent.com/${GITHUB_SOURCE}/${GITHUB_BRANCH}/index.yaml 2>/dev/null
-    HELM_INDEX="${BASE_DIR}/index.yaml"
+    # Update Chart.yaml and values.yaml from the package file metadata
+    # Use the script from the template repository
+    echo -e "${CYAN}Patching Helm chart template${RESET}"
+
+    CHART=${CHART_FOLDER} REGISTRY="${REGISTRY}" ORG="${REGISTRY_ORG}" PACKAGE_JSON=${BASE_DIR}/pkg/${pkg}/package.json ${CHART_TEMPLATE}/scripts/patch
+
+    # Copy README file from the plugin to the Helm chart, if there is one
+    if [ -f "./pkg/${pkg}/README.md" ]; then
+      cp ./pkg/${pkg}/README.md ${CHART_FOLDER}/README.md
+    fi
+
+    pushd ${CHART_FOLDER}/templates > /dev/null
+    
+    if [ "${GITHUB_BUILD}" == "true" ]; then
+      echo "Patching for GitHub build"
+      ENDPOINT=https://raw.githubusercontent.com/${GITHUB_SOURCE}/${GITHUB_BRANCH}/extensions/${pkg}/${PKG_VERSION}
+    else
+      echo "Patching for container build"
+      ENDPOINT=http://${IMAGE_PREFIX}${BASE_EXT}-svc.cattle-ui-plugin-system:8080/plugin/${PKG_NAME}
+    fi
+    sed -i.bak -e 's@endpoint: .*@endpoint: '"${ENDPOINT}"'@g' cr.yaml
+    rm *.bak
+    popd > /dev/null
+
+    # Additional patches
+    ${SCRIPT_DIR}/helmpatch ${CHART_FOLDER} "${BASE_DIR}/pkg/${pkg}/package.json"
+
+    # Package into a .tgz helm chart
+    helm package ${CHART_FOLDER} -d ${ASSETS}/${pkg}
+
+    # --------------------------------------------------------------------------------
+    # Update the helm index just for this chart 
+    # --------------------------------------------------------------------------------
+    HELM_INDEX=${BASE_DIR}/index.yaml
 
     if [ -f "${HELM_INDEX}" ]; then
       UPDATE="--merge ${HELM_INDEX}"
+    elif [ "${GITHUB_BUILD}" == "true" ] && [[ -n ${GITHUB_SOURCE} ]]; then
+      # Check if git branch contains index.yaml
+      GITHUB_SOURCE=$(echo -e "${GITHUB_SOURCE}" | sed 's/https:\/\///g')
+
+      wget -P ${BASE_DIR} https://raw.githubusercontent.com/${GITHUB_SOURCE}/${GITHUB_BRANCH}/index.yaml 2>/dev/null
+      HELM_INDEX="${BASE_DIR}/index.yaml"
+
+      if [ -f "${HELM_INDEX}" ]; then
+        UPDATE="--merge ${HELM_INDEX}"
+      fi
     fi
+
+    # Base URL referencing assets directly from GitHub
+    BASE_URL="assets/"
+
+    # Relative URL references assets within the container deployment
+    RELATIVE_URL="plugin/"
+    
+    rm -rf ${CHART_TMP}
+    mkdir -p ${CHART_TMP}
+    cp ${ASSETS}/${pkg}/*.tgz ${CHART_TMP}
+
+    if [ "${GITHUB_BUILD}" == "true" ]; then
+      helm repo index ${ASSETS} --url ${BASE_URL} ${UPDATE}
+    elif ! [ -e "${HELM_INDEX}" ]; then
+      helm repo index ${ASSETS} --url ${RELATIVE_URL}
+    fi
+
+    BUILT="true"
   fi
+done
 
-  # Base URL referencing assets directly from GitHub
-  BASE_URL="assets/"
-
-  # Relative URL references assets within the container deployment
-  RELATIVE_URL="plugin/"
-  
-  if [ "${GITHUB_BUILD}" == "true" ]; then
-    helm repo index ${ASSETS} --url ${BASE_URL} ${UPDATE}
-  elif ! [ -e "${HELM_INDEX}" ]; then
-    helm repo index ${ASSETS} --url ${RELATIVE_URL}
-  fi
-fi
-
-if [ "${GITHUB_BUILD}" == "true" ] && [[ -n "${GITHUB_RELEASE_TAG}" ]] && [ "${BUILT}" == "false" ]; then
-  echo -e "${YELLOW}Github release tag ${RESET}${BOLD}${GITHUB_RELEASE_TAG}${RESET}${YELLOW} did not match any package name.${RESET}"
-  echo -e "${YELLOW}Stopping build${RESET}"
-
-  rm -rf ${CHART_TMP}
-  rm -rf ${TMP} 
-  exit 1
-fi
-
-if [ -f ${ROOT_INDEX} ] && [ "${GITHUB_BUILD}" == "false" ]; then
+if [ -f ${ROOT_INDEX} ]; then
   UPDATE="--merge ${ROOT_INDEX}"
   helm repo index ${ASSETS} ${UPDATE}
 fi
 
-if [ -f ${ASSETS}/index.yaml ] && ! [ -e "${ROOT_INDEX}" ]; then
+if [ -f ${ASSETS}/index.yaml ]; then
   cp ${ASSETS}/index.yaml ${BASE_DIR}
 fi
 
 if [ "${GITHUB_BUILD}" == "false" ]; then
+  EXT_VERSION=$(jq -r .version ${BASE_DIR}/package.json)
+
+  if [ -z ${EXT_VERSION} ]; then
+    EXT_VERSION="0.0.0"
+  fi
+
   echo -e "${CYAN}Base extension: ${BASE_EXT}${RESET}"
   echo -e "${CYAN}Extension version: ${EXT_VERSION}${RESET}"
 
-  # Build the container image
-  ${SCRIPT_DIR}/bundle "${BASE_EXT}" "${EXT_VERSION}" "${REGISTRY}" "${REGISTRY_ORG}" "${IMAGE_PREFIX}" "${PUSH}" "${PODMAN_CONTAINER}"
+  # Build the docker image
+  ${SCRIPT_DIR}/bundle ${BASE_EXT} ${EXT_VERSION} ${REGISTRY} ${REGISTRY_ORG} ${IMAGE_PREFIX} ${PUSH}
 else
   rm -rf ${CHART_TEMPLATE}
 fi
 
 if [ "${GITHUB_BUILD}" == "true" ] && [ -f ${ROOT_INDEX} ]; then
-  if [[ -n "${GITHUB_RELEASE_TAG}" ]] && [ -f ${ASSETS}/index.yaml ]; then
-    cp ${ASSETS}/index.yaml tmp
-  else
-    cp ${ROOT_INDEX} tmp
-  fi
+  cp ${ROOT_INDEX} tmp
 fi
 
 if [ "${GITHUB_BUILD}" == "true" ] && [ "${BUILT}" == "true" ]; then
@@ -472,5 +346,5 @@ fi
 rm -rf ${CHART_TMP}
 
 if [ "${GITHUB_BUILD}" == "false" ]; then
-  rm -rf ${TMP} ${ASSETS} ${CHARTS} ${BASE_DIR}/extensions ${BASE_DIR}/dist-pkg ${ROOT_INDEX}
+  rm -rf ${TMP}
 fi
